Home task №3 ready for review
KseniaShurina/Coherent-solutions-.NET-School pull request #3
Opened 2024-10-28 13:31 UTC by KseniaShurina

2024-10-30 12:18 UTC, IgorKheidorov requested changes
Please fix comments and ask for a review again

2024-10-30 12:18 UTC, IgorKheidorov commented on HW3/Task31/Queue.cs
> +    {
Not good idea to provide public access to elements of Queue, somebody can brake the structure, make it private and as a result refactor Tail() method)))

2024-10-30 12:18 UTC, IgorKheidorov commented on HW3/Task31/Queue.cs
> +        {
Poor performance, you will allocate memory and copy elements each time you add or remove elements. Think how to avoid memory allocation each time. Think that size is fixed (for example, =10), allocate memory in constructor once, and provide the required functionality

2024-10-30 12:18 UTC, IgorKheidorov commented on HW3/Task31/Extensions/TailExtension.cs
> +            for (int i = 0; i < newArray.Length; i++)
think that ArrayOfElements is private, and refactor method

2024-10-31 18:48 UTC, KseniaShurina commented
I refactored the logic but I'm not satisfied with how it looks

2024-10-31 18:49 UTC, KseniaShurina commented on HW3/Task31/Queue.cs
> +        public void Foreach()
It's look strange)))

2024-11-01 13:18 UTC, IgorKheidorov requested changes
Please read comments
1. Create extension method Tail() -> your method is not an extension one
2.  Memory allocation is valid in constructor, and in Tail() method only. In other locations is forbidden )
3. If troubles  ask me for help )))))

2024-11-01 13:18 UTC, IgorKheidorov commented on HW3/Task31/Extensions/TailExtension.cs
> +    {
This is not an extension method )) =>Create a universal extension method Tail<T>() for the IQueue<T> interface. This method returns a new queue consisting of the elements of the original parameter queue minus the first element.

2024-11-01 13:18 UTC, IgorKheidorov commented on HW3/Task31/Program.cs
> +Console.WriteLine("\n Return queue without first item:");
Call of extension method looks like var tailQueue = queue.Tail(),  please fix ))

2024-11-01 13:18 UTC, IgorKheidorov commented on HW3/Task31/Queue.cs
> +
do not allocate array here, pure performance )
Memory allocation is valid in constructor, and in Tail() method only. In other locations is forbidden )

2024-11-12 11:30 UTC, IgorKheidorov approved these changes
Cool

2024-11-14 19:31 UTC, merged