Task №5 ready for review
KseniaShurina/Coherent-solutions-.NET-School pull request #5
Opened 2024-11-14 19:29 UTC by KseniaShurina

There are some troubles in Task 5.2 regarding LINQ expressions

2024-11-14 19:39 UTC, KseniaShurina commented on HW5/Task52/Catalog.cs
> +        // TODO Get from the catalog a set of tuples of the form “author’s name – the number of his books in the catalog” for all authors.
I have no idea how to write LINQ here

2024-11-15 13:33 UTC, IgorKheidorov requested changes
Please fix

2024-11-15 13:33 UTC, IgorKheidorov commented on HW5/Task51/SparseMatrix.cs
> +            {
move to private method

2024-11-15 13:33 UTC, IgorKheidorov commented on HW5/Task51/SparseMatrix.cs
> +
Ternary + LINQ

2024-11-15 13:33 UTC, IgorKheidorov commented on HW5/Task51/SparseMatrix.cs
> +        // Method returns non-zero elements with itself indexes ordered by column
LINQ

2024-11-15 13:33 UTC, IgorKheidorov commented on HW5/Task51/SparseMatrix.cs
> +                // If the value with these coordinates already exists change the value
check for 0

2024-11-15 13:33 UTC, IgorKheidorov commented on HW5/Task51/SparseMatrix.cs
> +        {
multiline

2024-11-15 13:33 UTC, IgorKheidorov commented on HW5/Task52/Entities/Book.cs
> +        // A collection of non-repeating strings, possibly empty
HashSet<string>,use constructor , remove Add, delete methods

2024-11-15 13:33 UTC, IgorKheidorov commented on HW5/Task52/Entities/Isbn.cs
> +            {
code style

2024-11-15 13:33 UTC, IgorKheidorov commented on HW5/Task52/Entities/Isbn.cs
> +        {
Regexp to const

2024-11-15 13:33 UTC, IgorKheidorov commented on HW5/Task52/Entities/Catalog.cs
> +                .ToList();
Remove

2024-11-15 13:33 UTC, IgorKheidorov commented on HW5/Task52/Entities/Catalog.cs
> +        public List<(Author, int)> GetAllAuthors()
SelectMany
GroupBy
Select

2024-11-15 13:33 UTC, IgorKheidorov commented on HW5/Task52/Entities/Catalog.cs
> +                .FirstOrDefault();
Remove

2024-11-15 13:33 UTC, IgorKheidorov commented on HW5/Task52/Entities/Isbn.cs
> +            if (!Regex.IsMatch(isbn, @"\d{3}-?\d{1}-?\d{2}-?\d{6}") && !Regex.IsMatch(isbn, @"^\d{12}$"))
IsbnNumber = isbn;

2024-11-19 13:38 UTC, IgorKheidorov approved these changes
Ok)

2024-11-19 14:09 UTC, merged